apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: farm-dora-auth-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dora-farm/farm-dora-helm-charts.git
    targetRevision: HEAD
    path: farm-dora-auth  # Helm 차트 경로
    helm:
      valueFiles:
        - values.yaml
      values: |
        image:
          repository: chakisuk/farm-dora-auth
          tag: latest
        service:
          port: 8040
        environment: dev
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 512Mi
        livenessProbe:
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: farmdora-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true