apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: farm-dora-activity-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dora-farm/farm-dora-helm-charts.git
    targetRevision: HEAD
    path: farm-dora-activity  # Helm 차트 경로
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: farmdora-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true