apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: farm-dora-ingress
  namespace: farmdora-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|mjs)$) {
        add_header Content-Type application/javascript;
        add_header X-Content-Type-Options nosniff;
      }
spec:
  ingressClassName: nginx
  rules:
#    - host: farmdora.kro.kr  # 배포환경 도메인
    - http:
        paths:
          - path: /api/activity
            pathType: Prefix
            backend:
              service:
                name: farm-dora-activity-dev
                port:
                  number: 8010
          - path: /api/buyer
            pathType: Prefix
            backend:
              service:
                name: farm-dora-buyer-dev
                port:
                  number: 8020
          - path: /api/search
            pathType: Prefix
            backend:
              service:
                name: farm-dora-search-dev
                port:
                  number: 8030
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: farm-dora-auth-dev
                port:
                  number: 8040
          - path: /api/product
            pathType: Prefix
            backend:
              service:
                name: farm-dora-product-dev
                port:
                  number: 8050
          - path: /assets/(.*\.js)$
            pathType: ImplementationSpecific
            backend:
              service:
                name: farm-dora-client-dev
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: farm-dora-client-dev
                port:
                  number: 80